name: 'Warn for main merge in PR'
description: 'A Github Action that adds a comment to a PR when a non-staging branch is the source and main the target'
inputs:
        allowedSourceBranchName: 'staging'
        targetBranchName: 'main'
        
