on: pull_request
jobs:
  warn_main_merge:
    runs-on: 'ubuntu-latest'
    name: 'Validate PR Source and Target Branches'
    steps:
      - name: 'Checking source and target branch in PR'
        uses: 'technologiestiftung/warn-for-main-merge-action@v1.5'
